### ISSUE TITLE
Inconsistencies with SatFunctions.CalculatePasses()

### ISSUE THREAD

**Issue by linmar22** [1manprojects/one_Sgp4#30] opened 2023-04-30 22:46 UTC
**Describe the bug**
Calling CalculatePasses(...) every 10 seconds produces a number of passes that fluctuates by 1 or 2.

**To Reproduce**
TLE: 
```
NOAA 18
1 28654U 05018A   23120.55018578  .00000249  00000+0  15728-3 0  9996
2 28654  98.9107 195.1690 0014973 151.5076 208.6918 14.12924038924756
```

Calling it on a 10-second `System.Timers.Timer` via

```csharp
var spgTle = ParserTLE.parseTle(tle.Line1, tle.Line2, tle.Name);
var passes = SatFunctions.CalculatePasses(observer, spgTle, new EpochTime(DateTime.Now), 10, 2);
```

**Expected behavior**
The number of passes is the same in a given 10-second time span.

**Additional context**
Observed `passes.Count()` fluctuate between 19 and 21. Seems like between these inconsistencies, the only thing that changes in the passes themselves is the seconds of the start/maxEl/end times. Confirmed that the only variable factor from the input is DateTime.Now, so seems like it could be some sort of rounding or parsing problems with the EpochTime (?). Tried turning the resolution up to 1 as well, with the same results. Obviously the number of passes in a given time period will fluctuate as the satellite completes orbits and time moves forward, but randomly increasing and decreasing every 10 seconds is a bit too frequent to be a coincidence😁

**Comment by linmar22** [comment] 2023-05-01 09:58
Some more testing shows that it's specifically the milliseconds of the times as well as the decimals of the azimuths and elevations that fluctuate.

**Comment by 1manprojects** [comment] 2023-05-05 14:12
From what you have written you are calling the CalculatePasses every 10 Seconds with a Timer. That function is designed to calculate all Passes for a long time period and should not be called every 10 seconds.
In your example above the call
`SatFunctions.CalculatePasses(observer, spgTle, new EpochTime(DateTime.Now), 10, 2);`
Would Calculate all passes starting from DateTime.Now to DateTime.Now + 2Days in a 10 Second steps. That means it will calculate the position of the satellite relative to the observer every 10 seconds and determine if it is visible. If the satellite is visible it will be returned as a pass with starting time and end time.

The SGP4 Model is not the most accurate model it will only guaranty a accuracy of the Satellite position of plus/minus 1km in all three axis (x,y,z) at best. the real position might even be off a lot more depending on how old the TLE data is and how far in the future one calculates the passes. Therefore fluctuations are normal. Depending on the Position of the Observer and given time frames the number of passes could fluctuate because at a certain point the satellite might just be out of sight and the pass will not be included, since the calculation will only calculate a single step every 10 seconds. 

I also cannot reproduce youre described problem since i do not know your observers position or the exact dates used to calculate the passes.

**Comment by 1manprojects** [comment] 2023-05-07 08:43
On further thought on this it is expected behaviour to have different number of passes wen calling `var passes = SatFunctions.CalculatePasses(observer, spgTle, new EpochTime(DateTime.Now), 10, 2);` with a timer every 10 seconds.
Since it will calculate the passes for the next to days in advance and if you move forward in time there will be points were the first pass of the last calculation is no longer available since the satellite has moved on.

Closing this Issue.

**Closed as completed by 1manprojects** 2023-05-07 08:43 UTC
Labels: expected behavior
