### ISSUE TITLE
Add the brightness (magnitude) to the Pass details

### ISSUE THREAD

**Issue by edetoc** [1manprojects/one_Sgp4#21] opened 2020-05-31 19:35 UTC
**Is your feature request related to a problem? Please describe.**
Would it be possible to add the brightness (magnitude) to the Pass details?

**Describe the solution you'd like**

Below are some passes as found on Heavens-above:

![image](https://user-images.githubusercontent.com/17158589/83361066-161a7800-a386-11ea-8d10-6015154767e3.png)

for each pass we have the brightness (magnitude) value. It would be great if One_Sgp4 can provide the same information (it seems this info is currently missing). 

Thanks!

**Comment by 1manprojects** [comment] 2020-05-31 19:42
To calculate the exact brightness you would need to know the albedo of a body, its position relative to its observer, and the area visible. To accurately calculate the brightness the information of the albedo and size of the object would be necessary and this information is currently not provided in the TLE Data. Thus they would need to be provided by external sources.

**Comment by 1manprojects** [comment] 2020-05-31 20:09
Duplicate of #6

**Comment by edetoc** [comment] 2020-05-31 20:12
thank you. I wrongly assumed this could be calculated based on the TLE only. I'm not sure how Heavens-above does to get this information... I am actually using the magnitude value to rank the visiblity of the pass . See below screenshot. maybe others approaches exist to achieve the same.

![image](https://user-images.githubusercontent.com/17158589/83361736-a4ddc380-a38b-11ea-9b6b-8763f43ef40b.png)

**Comment by 1manprojects** [comment] 2020-05-31 20:28
In most cases, these websites have a database with more information available to calculate the magnitude and others make a good educated guess depending on the sun's position and the satellite position based from the observer.

**Comment by edetoc** [comment] 2020-05-31 20:40
Thank you! To close the thread and to add on top of what you said here's what I found on https://heavens-above.com/faq.aspx

**How do you estimate the brightness of a satellite?**

_The brightness of a spacecraft is influenced by several factors, including its size, orientation, reflectivity of its surfaces, distance from the observer, and the angle between the sun, spacecraft and observer. The size and reflectivity determine the "intrinsic" brightness, and this is either estimated from observations or from a knowledge of the size and type of coverings used in the construction. The distance, and sun-satellite-observer angle can all be calculated from the orbit. This leaves just the orientation or attitude, which is usually unknown, and often varying rapidly (e.g. a tumbling rocket body). For this reason, our magnitude estimates should only be treated as a rough guide, and the actual brightness you see could be considerably more or less than this._

**Closed as completed** 2020-05-31 20:59 UTC
Labels: duplicate
