### ISSUE TITLE
CalculatePasses result doesn't match Heavens-above.com results

### ISSUE THREAD

**Issue by edetoc** [1manprojects/one_Sgp4#20] opened 2020-05-31 19:23 UTC
**Describe the bug**
I'm using One_Sgp4 v1.0.11.
I'm trying to use CalculatePasses method to get sighting predictions for the ISS. I'm comparing the results returned by CalculatePasses with predictions obtained from Heavens-Above.com for the same location, same day, but I observe different results.

**To Reproduce**

1. What data was used for the bug (e.g. TLE-Data, Date, Time ..)

TLE obtained from Celestrak for ISS on May 31st (https://celestrak.com/satcat/tle.php?CATNR=25544)

ISS (ZARYA)             
1 25544U 98067A   20152.27581124  .00000174  00000-0  11188-4 0  9995
2 25544  51.6441  72.1703 0002261  13.9081 125.7010 15.49399407229398

2. What function was called

CalculatePasses is called as below:

```
            var bSuccess = await TryGetTLESets();

            if (!bSuccess)
            {
                // tell user we couldn't fetch TLE or not found in local cache
                throw new FileNotFoundException();
            }

            var tleList = ParserTLE.ParseFile(Path.Combine(Windows.Storage.ApplicationData.Current.LocalFolder.Path,
                                                            "stations.txt"));

            var tleISS = tleList.Find(x => x.getNoradID() == "25544");  // return null if not found, otherwise the TLE for ISS

            //Coordinate of an observer on Ground lat, long, height(in meters)
            One_Sgp4.Coordinate observer = new Coordinate(48.858093, 2.294694, 0);   // 48.858093, 2.294694  => Eiffel Tower

            //Calculate the Next 5 Passes over a point
            //for a location, Satellite, StartTime, Accuracy in Seconds = 15sec, MaxNumber of Days = 5 Days, Wgs constant = WGS_84
            //Returns pass with Location, StartTime of Pass, EndTime Of Pass, Max Elevation in Degrees
            List<Pass> passes = One_Sgp4.SatFunctions.CalculatePasses(observer, tleISS, new EpochTime(DateTime.UtcNow), 10, 2, Sgp4.wgsConstant.WGS_84);

            Debug.WriteLine("START TIME:");

            foreach (var p in passes)
            {
                var pd = p.getPassDetailsAtStart();

                Debug.WriteLine(pd.ToString());
                
                
            }

```

3. What was the result and output

Results observed for above code and TLE is:

```
START TIME:

18:44:36 : Elevation: 0.596397746612726°, Azimuth 286.501538004863°, Range 2299.30172721437km 
20:21:26 : Elevation: 0.581273626386928°, Azimuth 289.589556700608°, Range 2302.70192885187km 
21:58:46 : Elevation: 0.224917594272741°, Azimuth 275.738975381313°, Range 2339.95580465039km 
13:08:26 : Elevation: 0.0444936882516238°, Azimuth 173.462625055011°, Range 2340.306324557km 
14:42:56 : Elevation: 0.426040211060339°, Azimuth 223.5007745911°, Range 2302.44754914584km 
16:19:26 : Elevation: 0.331834095560812°, Azimuth 259.584712050285°, Range 2320.59706403633km 
17:56:26 : Elevation: 0.0955231688512556°, Azimuth 282.432782758386°, Range 2352.72291602485km 
19:33:26 : Elevation: 0.574601663417893°, Azimuth 290.262387553938°, Range 2302.94493966847km 
21:10:26 : Elevation: 0.305351401410957°, Azimuth 282.291634222747°, Range 2331.83059685543km 
12:22:26 : Elevation: 0.24334422268383°, Azimuth 148.617524370182°, Range 2320.39585586617km 
13:55:16 : Elevation: 0.197594926130708°, Azimuth 210.804526904679°, Range 2325.32322597625km 
15:31:26 : Elevation: 0.40181438101692°, Azimuth 250.205784968407°, Range 2310.49065301218km 
17:08:26 : Elevation: 0.313512743787331°, Azimuth 277.314123150284°, Range 2327.03545020543km 
```

4. If result was not what you expected with what was is compared to and from where does this information come from

Results from heavens-above for same GPS location are:

![image](https://user-images.githubusercontent.com/17158589/83360710-99869a00-a383-11ea-946d-86d8a60aebe8.png)

**Expected behavior**
I would expect that the results match. However the pass for May 31st returned by heavens-above is not found by CalculatePasses

**Version(please complete the following information):**
- Device: Desktop PC
 - OS: Windows 10 
 - Version 1909

**Question:**
Am I using CalculatePasses incorrectly or is there a bug in this method?

thank you!

**Comment by 1manprojects** [comment] 2020-05-31 19:42
Thank you for the Information I will investigate the issue.

**Comment by 1manprojects** [comment] 2020-06-01 09:26
You are using new EpochTime(DateTime.UtcNow) to determine the Start of the Calculations. However, since I do not know what exact time was used for your calculations I can not reproduce the error you describe.
I have tested it currently with all passes on the 31. Mai of 2020 and 1.June 2020 and compared the outputs against PreviSat and Heavens-Above and could not find any error.

**Comment by edetoc** [comment] 2020-06-01 11:22
thanks. I have changed the code to output DateTime.UtcNow when I do the test:

```
 One_Sgp4.Coordinate observer = new Coordinate(48.858093, 2.294694, 0);   // 48.858093, 2.294694  => Eiffel Tower

//Calculate the Next 5 Passes over a point
//for a location, Satellite, StartTime, Accuracy in Seconds = 15sec, MaxNumber of Days = 5 Days, Wgs constant = WGS_84
//Returns pass with Location, StartTime of Pass, EndTime Of Pass, Max Elevation in Degrees

Debug.WriteLine("About to call CalculatePasses for Start time (UTC Now) : " + DateTime.UtcNow);

List<Pass> passes = One_Sgp4.SatFunctions.CalculatePasses(observer, tleISS, new EpochTime(DateTime.UtcNow), 10, 2, Sgp4.wgsConstant.WGS_84);

Debug.WriteLine("Passes Start time:");

foreach (var p in passes)
{
	var pd = p.getPassDetailsAtStart();

	Debug.WriteLine(pd.time.toDateTime());
}
```

This is what I get:

```
About to call CalculatePasses for Start time (UTC Now) : 6/1/2020 11:14:09 AM
Passes Start time:
6/1/2020 1:08:29 PM
6/1/2020 2:42:59 PM
6/1/2020 4:19:39 PM
6/1/2020 5:56:39 PM
6/1/2020 7:33:29 PM
6/1/2020 9:10:39 PM
6/2/2020 12:22:09 PM
6/2/2020 1:55:19 PM
6/2/2020 3:31:39 PM
6/2/2020 5:08:39 PM
6/2/2020 6:45:29 PM
6/2/2020 8:22:29 PM
6/2/2020 10:01:29 PM
```

As a comparison here's what I get on Heavens-Above (same ground observer):

![image](https://user-images.githubusercontent.com/17158589/83403968-02b0f080-a40a-11ea-871f-013b4af34f7a.png)


![image](https://user-images.githubusercontent.com/17158589/83403940-f75dc500-a409-11ea-83e7-753f8380ccfd.png)

As you can see I do not see the Pass starting June 1st at 23:13:29 in the results returned by CalculatePasses.

**Comment by 1manprojects** [comment] 2020-06-06 12:25
First of all, there is a bug in the EpochTime that would print the wrong date and this will be fixed soon.

However, I cannot verify any data from Heavens above with the output of the OneSGP library. Heavens above will only list Passes in which the satellite is visible, which means it is reflecting sunlight and thus can be seen visually from the location, this is the visible only checkbox. And it will not show certain passes that are only a few minutes.

The OneSGP will calculate ALL passes that would allow direct communication with the satellite.  
I have tested multiple times the passes calculated and crosschecked the output with PreviSat and PREDICT and OneSGPs output matches with those.

**Comment by 1manprojects** [comment] 2020-06-06 12:32
I will be closing this Issue. If you can reproduce this problem with another PassPreciction tool/Software you can create a new Issue.

For More Information, I would recommend you to read the FAQ of heavens above 
https://heavens-above.com/faq.aspx

**Closed as completed by 1manprojects** 2020-06-06 12:32 UTC
Labels: expected behavior
