### ISSUE TITLE
Latitude and longitude is WAY off

### ISSUE THREAD

**Issue by njbrown09** [1manprojects/one_Sgp4#8] opened 2018-11-04 21:03 UTC
Latitude and longitude from calcSpherePoint is way off. Try it on the latest library version. Compared to websites like n2yo and heavens above, its extremely off

**Comment by njbrown09** [comment] 2018-11-04 21:50
i think it has somehting to do with the timne. When i give it DateTime.UtcNow, it doesnt give me the current position. It appears that it does give an accurate position, but not for the right time

**Comment by njbrown09** [comment] 2018-11-05 03:34
Could it be something to do with daylight savings maybe?

**Comment by 1manprojects** [comment] 2018-11-05 08:15
At first look it appears the calculation are really off as for the reason I am still investigating. Could be that the Mean Greenwich Time is calculated wrong for the Position on ground or that the calculation of the lat. and long. are incorrect.

**Comment by edetoc** [comment] 2018-11-05 08:57
> i think it has somehting to do with the timne. When i give it DateTime.UtcNow, it doesnt give me the current position. It appears that it does give an accurate position, but not for the right time

I notice the same in my app which uses one_Sgp4. it used to work fine. Really looks like daylight savings is the root cause.

**Comment by 1manprojects** [comment] 2018-11-05 09:13
Currently i do not think that it would be since all calculations are done in UTC time and that does not have daylight savings time. However i will recheck it as soon as i have time.

**Comment by njbrown09** [comment] 2018-11-05 13:15
I’m quite sure it has something to do with daylight savings. I tested one
of my old applications that would point my telescope at satellites and it’s
way off also. It worked fine before

**Comment by njbrown09** [comment] 2018-11-05 19:29
Ive been looking into it more and from what i have been seeing, i think that daylight savings is the root cause, but just removing an hour from the time wont fix it. Ive been getting longitude sometimes of -455 which is impossible

**Comment by njbrown09** [comment] 2018-11-06 20:48
anyone able to find a lead on this issue? Ive been searching for hours.

**Comment by 1manprojects** [comment] 2018-11-07 08:08
Sorry but i did not had the time yet to analiyse the issue thourugh like i wold to.

**Comment by 1manprojects** [comment] 2018-11-10 10:49
So i finally found the problem. The calculation for the latitude were off after i introduced a Function to get a higher accuracy. I will try to fix this in the next few days and publish an update.

**Comment by edetoc** [comment] 2018-11-10 15:02
Thank you. 
Question: 
Does the bug you found also affects the results produced by runSgp4Cal() ? in fact, using a fresh TLE for the ISS (obtained from https://www.celestrak.com/NORAD/elements/stations.txt), I can see a mismatch regarding the current Lat/Long of the Space Station when comparing with http://www.esa.int/Our_Activities/Human_Spaceflight/International_Space_Station/Where_is_the_International_Space_Station.  I'm using One_Sgp4 v1.0.4. Once again this used to work fine until recently (approx when the daylight saving ended). thanks again.
Eric

**Comment by 1manprojects** [comment] 2018-11-10 15:11
The Bug does not affect the calculations of the position of the satellite itself but only the calculations for the Lat. and Long. values using the functions calcSatSubPoint. And Version 1.0.4 was published around the time of the Daylight saving time. For the calculations itself one should always use UTC time were daylight savings does not exist.

**Comment by edetoc** [comment] 2018-11-10 15:28
Thanks for your reply. I just checked my code and confirmed I'm calling calcSatSubPoint so I assume I'm hitting this bug. Looking forward to your fix to be released :-)

**Comment by edetoc** [comment] 2018-11-15 13:39
Have you managed to make progress on the fix?
thanks in advance

**Comment by 1manprojects** [comment] 2018-11-16 11:15
Still work in progress. A new fixed release will be available, if everything goes as planned, in around 1 week

**Comment by edetoc** [comment] 2018-11-25 18:37
sorry for chasing. are you still on  track to release the fix soon?
Thanks in advance

**Comment by 1manprojects** [comment] 2018-11-26 19:40
Currently still a work in progress, due to time limitations i did not had have enough time until now to work on it.

**Comment by edetoc** [comment] 2018-11-26 20:09
no worries , thanks for looking into this

**Comment by njbrown09** [comment] 2018-11-26 23:11
Thanks for looking into this

**Comment by 1manprojects** [comment] 2018-12-02 12:27
Issue has been fixed with commit #889cf88 and new version has been published to Nuget

**Closed as completed by 1manprojects** 2018-12-02 12:27 UTC
Labels: bug
